mysql:
    host: 127.0.0.1
    port: 3306
    config: ""
    db: gvb_db
    user: root
    password: root
    log_level: dev
logger:
    level: info
    prefix: '[gvb]'
    director: log
    show_line: false
    log_in_console: false
system:
    host: 127.0.0.1
    port: 8080
    env: release
upload:
    size: 2
    path: uploads/file
site_info:
    created_at: "2026-2-10"
    title: 包包的个人博客
    email: 484267528@qq.com
    name: 耄耋
    job: 学生
    addr: 安徽 池州
    slogan: 哈吉耄耋
    github_url: https://github.com/484267528-design/gvb_server
qq:
    app_id: xx
    key: xx
    redirect: http://xx.xx.com/login?flag=qq
qin_iu:
    enable: false
    access_key: UMM-xx-FdRIf-xx
    secret_key: xx
    bucket: bao_bao_zhi_dao
    cdn: xx://xx.xx.com/
    zone: xx
    size: 5
email:
    host: smtp.qq.com
    port: "465"
    user: 484267528@qq.cpm
    password: xxx
    default_from_email: 包包知道
    user_ssl: true
    user_tls: false
jwt:
    secret: xxx
    expires: 48
    issuer: xx
